services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    #volumes: 
    #  - ./frontend:/app/frontend
    #  - /app/frontend/node_modules
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore:
            - node_modules/
            - .next/
        - path: ./frontend/package.json
          action: rebuild          

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '3001:3001'
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - node_modules/
            - dist/
        - path: ./backend/package.json
          action: rebuild

  database:
    image: mongo:8
    env_file:
      - .env
    ports:
      - 27017:27017
    #volumes: 
    #  - database-data:/data/db

#volumes:
  #database-data:   
