services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://database:27017/mongodb
    ports:
      - 3001:3001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
